# Generated by Django 5.0.4 on 2024-10-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('class_type', models.CharField(choices=[('CBSE', 'CBSE'), ('JEE', 'JEE'), ('NEET', 'NEET')], max_length=4)),
                ('preferred_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Class Booking',
                'verbose_name_plural': 'Class Bookings',
            },
        ),
    ]
