# Generated by Django 5.0.4 on 2024-10-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classbooking',
            options={},
        ),
        migrations.AlterField(
            model_name='classbooking',
            name='class_type',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('JEE', 'JEE'), ('NEET', 'NEET'), ('One-to-One', 'One-to-One')], max_length=10),
        ),
    ]
